apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
  namespace: andy
spec:
  #gke
  storageClassName: standard
  #storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi