apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: andy
  labels:
    app: mysql
spec:
  #gke
  storageClassName: standard
  #storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi