apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: andy
  labels:
    app: wordpress
spec:
  #SDK
  type: LoadBalancer
  # type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress