apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: grafana
  labels:
    app: grafana
spec:
  #SDK
  type: LoadBalancer
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: grafana